src/cell/mod.rs, src/cell/store.rs, src/lib.rs, src/redis/mod.rs
Moves `try!` to the newly released, and more visually pleasing, `?`
operator.
=> Switch `try!` macro to 1.13's `?` operator

src/redis/raw.rs
Smart of the Rust compiler to finally pick up on these (as of 1.13.0).
=> Add `unsafe` invocations around calls on extern static

Cargo.toml, src/cell/store.rs, src/error.rs, src/lib.rs, src/redis/mod.rs, src/redis/raw.rs
Switch to use low level Redis module APIs (i.e. off of the more blunt `CALL`
API). Theoretically this should result in improved performance (but in practice
doesn't seem to make a huge difference),
=> Use low level Redis module APIs

Cargo.toml, src/redis/raw.rs
Fixing this:  
```
[dwerner:~/Development/redis-cell]$ cargo build                                                                                                                                                                                                          (master✱) 
Compiling redis-cell v0.1.0 (file:///home/dwerner/Development/redis-cell)
error: linking with `cc` failed: exit code: 1
|
= note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/home/dwerner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/home/dwerner/Development/redis-cell/target/debug/deps/redis_cell.0.o" "-o" "/home/dwerner/Development/redis-cell/target/debug/deps/libredis_cell.so" "/home/dwerner/Development/redis-cell/target/debug/deps/redis_cell.metadata. …
```
=> stick with one version of gcc, fix linking of redismodule

src/cell/store.rs
Fixes https://github.com/brandur/redis-cell/issues/11
The rationale for this check is already explained in existing code: https://github.com/brandur/redis-cell/blob/master/src/redis/mod.rs#L299-L304
As I'm not familiar to the code, I decided to modify it at the user side, but maybe a better solution might be to modify `RedisKeyWritable.read()` to return `None` for empty strings. What do you think @brandur?
=> Check for emptyness of writable string before parsing

src/cell/mod.rs
Previous code checked if the time was less than 1 second in the future, which produces incorrect results when the period between allowed requests is < 1 second (rate > 1/s).
Closes https://github.com/brandur/redis-cell/issues/12
=> Correctly check whether the time is in the past

.travis.yml, Makefile, rustfmt.toml, src/cell/mod.rs, src/cell/store.rs, src/error.rs, src/lib.rs, src/redis/mod.rs, src/redis/raw.rs
Runs a modern version of Rustfmt on the project (the one available via
the `rustup-preview` toolchain in `rustup`) and rewrites a large
majority of the code. This has the nice effect of making everything
quite a bit nicer because it seems that better conventions have won out
in the end.
We also:
* Add a check in CI to make sure new code has been properly fmt'ed.
* Port a few configuration options over from another one of my projects.
They're benign, and make things a little better.
* Adds a `Makefile` with an `all` target that will conveniently perform
every important check that will happen in CI.
Fixes #15.
=> Modernize Rustfmt conventions and rewrite everything

build.rs
It seems that the name `gcc::Config` was deprecated and that
`gcc::Build` is the new preferred replacement.
=> Rename `gcc::Config` to `gcc::Build`

Cargo.toml, src/redis/mod.rs, src/redis/raw.rs
Upgrades the `bitflags` package. This comes with some nice ergonomic
improvements in that individual values are now accessible from within a
struct instead of as package-level constants.
=> Upgrade `bitflags` package

.travis.yml, rustfmt.toml, src/cell/mod.rs, src/cell/store.rs, src/lib.rs, src/redis/mod.rs, src/redis/raw.rs
The build is currently broken because the method I was using to install
Rustfmt and Clippy is no longer working. Both these programs are now
available as stable components, so change the Travis sequence to take
advantage of that (and fix the build).
=> Rustfmt and Clippy are now available on the stable channel

Cargo.toml, build.rs
Apparently the former is now deprecated and the use of `cc` is
recommended now.
=> Switch from crate `gcc` to `cc`

src/cell/mod.rs, src/cell/store.rs
A nice trick that was suggested in [1] in which we remove the lifetime
(`'a`) from `RateLimiter` and instead give it just a basic `T:
store::Store`, and then enable a reference by implementing the `Store`
trait for `&'a mut T' where `T: Store`.
[1] https://github.com/brandur/redis-cell/issues/23
=> Remove `RateLimiter`'s lifetime

src/lib.rs
Fix command key info when create_command.
The command key info is used in redis cluster. Incorrect command key info will cause cluster can not redirect key to the correct node.
=> fix redis command key define

.travis.yml
Clippy is only available intermittently in nightly builds, and isn't
available right now which is breaking the build. Here we disable it for
nightly builds.
=> Remove Clippy from nightly builds

src/redis/mod.rs, src/redis/raw.rs
Adds a couple of minor enhancements to follow up #31:
* Adds some documentation around the design decisions of using
`RedisModule_ReplicateVerbatim`.
* Adds a response status to `RedisModule_ReplicateVerbatim` which we
handle for general hygiene even if it a non-OK response is never
expected.
=> Add more docs and a return status

README.md
Adds a new README section that includes information on how to run tests,
perform other checks, and release the project.
=> Add a development section to `README.md`

.travis.yml, rustfmt.toml, src/cell/mod.rs, src/cell/store.rs, src/redis/mod.rs
The unstable features I was using are still unstable (they appear to be
permanently so), and the situation's gotten worse in that Rustfmt seems
to not really be available in nightly builds anymore, which was the only
way that unstable features could be used.
For now, stop using those unstable features and stop running Rustfmt in
nightly, preferring only the stable channel instead.
=> Fix various Rustfmt problems in the build

.travis.yml
Apparently the Rust Cross project doesn't support FreeBSD anymore:
https://github.com/rust-embedded/cross/issues/274
https://github.com/rust-embedded/cross/issues/306
=> Disable FreeBSD target in Travis

.github/workflows/ci.yml
Get back to feature parity with the old Travis configuration where we
can cut releases and upload build artifacts via GitHub Actions.
=> Cut releases from GitHub Actions

src/lib.rs, src/redis/mod.rs
Here we add an invocation to `RedisModule_ReplicateVerbatim` so that
invoking `CL.THROTTLE` will replicate out to replicas/AOF.
This _also_ has the side effect of incrementing a dirty counter within
the Redis server so that RDB snapshots work properly, thus fixing #52.
=> Replicate `CL.THROTTLE` invocations to replicas/AOF

Makefile, src/cell/mod.rs, src/lib.rs
- since `--write-mode` is no longer supported, remove it from `Makefile->fmt`
- fix unnecessary cast
Signed-off-by: Tuan Anh Tran <me@tuananh.org>
=> chore: fix warnings + remove --write-mode since it's no longer supported

.github/workflows/ci.yml, src/cell/mod.rs, src/error.rs, src/redis/mod.rs, src/redis/raw.rs
Fix build errors that have crept in after a long winter without changes.
Also remove the special `build_nightly` job. Hopefully Rust is a bit
more stable now and this is no longer necessary.
=> Fix build errors after long pause

.github/workflows/ci.yml
Publish releases for the `aarch64-unknown-linux-gnu` target.
=> Publish to ARM64 for Linux

src/redis/mod.rs
Fix nightly build by removing Clippy references from `*.rs` file [1].
[1] https://github.com/brandur/redis-cell/actions/runs/9334075649/job/25691817287
=> Fix nightly build by removing Clippy references from `*.rs` file

Cargo.toml, src/cell/mod.rs, src/cell/store.rs, src/lib.rs, src/redis/mod.rs
To keep things somewhat current, upgrade all dependencies to latest
versions.
The hardest by far is `time`, which has broken its entire API surface
area, _again_. We make some fairly substantial code changes to
accommodate that.
I also changed the store API to use `u64`s instead of `i64`s since
they're working with nanoseconds. I realize in retrospect that this
change might not be needed since Redis works with a signed integer type,
but it improves the interface slightly in that a missing value is
returned as a `None` instead of `-1`, which is more Rust-like.
=> Upgrade version of dependencies + fix `time` breakages
